version: "2"
services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/app
    working_dir: /app
    depends_on: 
      - splash
      - phantomjs
  phantomjs:
    image: wernight/phantomjs:2
    ports:
      - "8910:8910"
    command: phantomjs --webdriver=8910
  splash:
    image: scrapinghub/splash:2.3.2
    ports:
      - 8050:8050
    restart: always
    # add --maxrss 1 GB on to normal docker entrypoint command
    entrypoint: python3 /app/bin/splash --proxy-profiles-path /etc/splash/proxy-profiles --js-profiles-path /etc/splash/js-profiles --filters-path /etc/splash/filters --lua-package-path /etc/splash/lua_modules/?.lua --maxrss 1000
