version: "2"
services:
  phantomjs:
    image: wernight/phantomjs:2
    ports:
      - "8910:8910"
    command: phantomjs --webdriver=8910
  my-scrapy-in:
    build:
     context: .
     dockerfile: Dockerfile.in
    volumes: 
      - .:/app
    working_dir: /app
    depends_on: 
      - phantomjs
  my-scrapy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/app
    working_dir: /app
    depends_on: 
      - phantomjs
